config/routes.rb
Rails.application.routes.draw do
  root 'bbs_pages#home'
  get  'help'    => 'bbs_pages#help'
  get  "bbsposts/create"
  get  "bbsposts/new"
  post "bbsposts" => "bbsposts#create"

  resources :bbsposts
end

app/models/bbspost.rb
class Bbspost < ActiveRecord::Base
  self.per_page = 10
  default_scope -> { order(created_at: :desc) }
  validates :title, presence: true, length: { maximum: 50 }
  validates :username, presence: true, length: { maximum: 20 }
  validates :content, presence: true, length: { maximum: 200 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/bbs_pages_controller.rb
# coding: utf-8
class BbsPagesController < ApplicationController

  def home
   @bbspost = Bbspost.page(params[:page])

#		@bbspost = Bbspost.all
#  	@bbspost[:title] = 'Sample Title'
#  	@bbspost[:username] = 'Sample Name'
#  	@bbspost[:content] = 'Test contents,no meaning.'

#    @bbspost = Bbspost.create
#    @bbspost.username = 'Sample Name'
#    @bbspost.title = 'Sample Title'
#    @bbspost.content = 'Test contents,no meaning.'
  end

  def help
  end
end

app/controllers/bbsposts_controller.rb
# -*- coding: utf-8 -*-

class BbspostsController < ApplicationController

  include ActiveModel::ForbiddenAttributesProtection

	def new
	  @bbspost = Bbspost.new
	end

  def create
	  @bbspost = Bbspost.new(bbspost_params)

    if @bbspost.save
      flash[:success] = "投稿ありがとうございます"
	    redirect_to root_path
    else
      flash.now[:danger] = "いずれかのデータが空、もしくは長すぎます"
      render 'new'
    end
  end

  def destroy
  end

  private

    def bbspost_params
      params.require(:bbspost).permit(:username, :title, :content)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bbs_pages_helper.rb
module BbsPagesHelper
end

app/helpers/bbsposts_helper.rb
module BbspostsHelper
end

app/views/bbs_pages/help.html.erb
# coding: utf-8
<h1>HELP?</h1>
<p>help me rather</p>

app/views/bbs_pages/home.html.erb
<div class="center jumbotron">
  <h1>
	<%= link_to image_tag("sample.png", alt: "BBS", class: "grow"),
            '/' %>
</h1>

  <h2>
    This is the BBS page
      <h3>
        <%= link_to "escape", "http://google.com/", class: "btn btn-sm btn-danger" %>
      <h3>
  </h2>
</div>
<p>
<%= link_to "POST", "bbsposts/new", class: "btn btn-sm btn-info btn-block" %>

<ul class="bbsposts">
	
	<%= page_entries_info @bbspost %></br>
	<%= will_paginate @bbspost %>
  <% @bbspost.each do |bbspost| %>
<li>
<%= bbspost.title %>
</li>
		<%= bbspost.content %>
(
		<%= bbspost.created_at.strftime("%Y %m/%d %H:%M:%S") %>
:
		<%= bbspost.username %>
)
  <% end %>
</br>
<%= will_paginate @bbspost %>
</ul>
</p>

app/views/bbsposts/_bbspost.html.erb
<li id="bbspost-<%= bbspost.id %>">
  <%= bbspost.username %>
  <span class="user"><%= link_to bbspost.username %></span>
  <span class="content"><%= bbspost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(bbspost.created_at) %> ago.
  </span>
</li>

app/views/bbsposts/create.html.erb
<div class="container">
	<%= form_for Bbspost.new do |f| %>

  <div class="row">
    <div class="col-sm-7" style="background-color:aliceblue;">
	 		<%= f.label :title %>
		</div>
    <div class="col-sm-5" style="background-color:aliceblue;">
		  <%= f.label :username %>
		</div>
  </div>

  <div class="row">
    <div class="col-sm-7" style="background-color:aliceblue;">
	 		<%= f.text_field :title, :size=>"50" %>
		</div>
    <div class="col-sm-5" style="background-color:aliceblue;">
		  <%= f.text_field :username, :size=>"25" %>
		</div>
  </div>

  <div class="row">
    <div class="col-sm-12" style="background-color:aliceblue;">
	 		<%= f.label :content %>
		</div>
  </div>

  <div class="row">
    <div class="col-sm-12" style="background-color:aliceblue;">
	 		<%= f.text_area :content, :size=>"90x8" %>
		</div>
  </div>

  <%= f.submit "POST" %>
	<% end %>
</div>

app/views/bbsposts/new.html.erb
<div class="container">
	<%= form_for Bbspost.new do |f| %>

	<div class="row">
		<div class="col-md-6 col-md-offset-3">

	 		<%= f.label :title %>
	 		<%= f.text_field :title, class: 'form-control'%>

		  <%= f.label :username %>
		  <%= f.text_field :username, class: 'form-control'%>

	 		<%= f.label :content %>
	 		<%= f.text_area :content, class: 'form-control' %>

		  <%= f.submit "投稿", class: "btn btn-primary" %>
		</div>
	</div>

	<% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Refer to the site <a href="http://railstutorial.jp/">Ruby on Rails Tutorial</a> shown below.
  </small>
  <nav>
    <ul>
      <li><%= link_to "Help",help_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "bbs", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Help", help_path %></li>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BBS</title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">

      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_bbspost_form.html.erb
<%= form_for(@bbspost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>